apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    creation_method: manual
    env: prod
spec:
  containers:
  - image: 344625735300.dkr.ecr.us-east-1.amazonaws.com/mysql:v0.2
    name: mysql
    ports:
    - containerPort: 3306
      protocol: TCP
env:
   name: MYSQL_ROOT_PASSWORD
   value: "pw"
