apiVersion: v1
kind: Pod
metadata:
  name: mywebapp
  labels:
    creation_method: manual
    env: prod
spec:
  containers:
  - image: 344625735300.dkr.ecr.us-east-1.amazonaws.com/mywebapp:v0.2
    name: mywebapp
    ports:
    - containerPort: 8080
      protocol: TCP
env:
  - name: DBUSER
   value: "root"
  - name: DBPWD
    value: "pw"
  - name: DBPORT
    value: "3306"
  - name: DBHOST
    value: "mysql.mysql.svc.cluster.local"
