apiVersion: apps/v1
kind: Replicaset
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  selector:
    matchLabels:
        app: mysql
  replicas: 3
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: 344625735300.dkr.ecr.us-east-1.amazonaws.com/mysql:v0.2
        # image: gcr.io/google-samples/gb-frontend:v4
        env: 
        - name: DBUSER
          value: "root"
        - name: DBPWD
          value: "pw"
        - name: MYSQL_ROOT_PASSWORD
          value: "pw"
        ports:
        - containerPort: 80